[package]
name = "hir"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ast = { path = "../ast" }
la-arena = "0.3.1"
lasso = "0.7"
miette = { version = "7", default-features = false, features = ["derive"] }
syntax = { path = "../syntax" }
thiserror = "2"

[dev-dependencies]
parse = { path = "../parse" }
