[workspace]
resolver = "3"
members = [
    "crates/tokens",
    "crates/lex",
    "crates/syntax",
    "crates/parse",
    "crates/ast",
    "crates/hir",
    "crates/infer",
    "crates/mir",
    "crates/jit",
    "crates/compile",
    "crates/vm",
    "crates/runtime",
    "crates/wasm",
    "crates/analyse",
    "crates/lsp",
    "crates/cli",
    "crates/bench",
]
