[workspace]
resolver = "3"
members = ["crates/*"]
exclude = ["crates/toy_lsp"]

[workspace.dependencies]
toy_compiler = { path = "crates/toy_compiler" }
toy_logger = { path = "crates/toy_logger" }
toy_lexer = { path = "crates/toy_lexer" }
toy_parser = { path = "crates/toy_parser" }
toy_typecheck = { path = "crates/toy_typecheck" }
toy_codegen = { path = "crates/toy_codegen" }
toy_tokens = { path = "crates/toy_tokens" }
toy_cst = { path = "crates/toy_cst" }
toy_ast = { path = "crates/toy_ast" }
toy_hir = { path = "crates/toy_hir" }
toy_mir = { path = "crates/toy_mir" }
toy_runtime = { path = "crates/toy_runtime" }
toy_resolve = { path = "crates/toy_resolve" }

log = "0.4"
thiserror = "2.0.17"
miette = { version = "7.6.0", features = ["fancy"] }
clap = { version = "4.5", features = ["derive"] }
lasso = { version = "0.7", features = ["multi-threaded", "serialize"] }
la-arena = "0.3.1"

[profile.release]
debug = false
opt-level = 3
lto = "thin"

[profile.optimized]
strip = true
panic = "abort"
inherits = "release"
codegen-units = 1
lto = "fat"

[profile.profiling]
inherits = "release"
debug = true
