[workspace]
resolver = "3"
members = [
    "crates/tokens",
    "crates/lex",
    "crates/syntax",
    "crates/parse",
    "crates/ast",
    "crates/hir",
    "crates/infer",
    "crates/mir",
    "crates/jit",
    "crates/compile",
    "crates/vm",
    "crates/runtime",
    "crates/wasm",
    "crates/analyse",
    "crates/lsp",
    "crates/cli",
    "crates/bench",
]

# Standard release
[profile.release]
opt-level = 3
debug = false

# Optimised (thin LTO)
[profile.optimised]
inherits = "release"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true

# Maximum optimisation (fat LTO, slow compile)
[profile.optimised-max]
inherits = "optimised"
lto = "fat"

[profile.profiling]
inherits = "release"
debug = true
