[package]
name = "jit"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
mir = { path = "../mir" }
vm = { path = "../vm" }
lasso = "0.7"
cranelift = "0.127.0"
cranelift-jit = "0.127.0"
cranelift-module = "0.127.0"
cranelift-native = "0.127.0"
target-lexicon = "0.13"
thiserror = "2"
