[package]
name = "toy_cli"
authors = ["Paul Lavender-Jones <paul@lavender-jones.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[[bin]]
name = "toy"
path = "src/main.rs"

[dependencies]
toy_compiler.workspace = true
toy_logger.workspace = true

log.workspace = true
miette.workspace = true
thiserror.workspace = true
clap.workspace = true
