[package]
name = "toy_hir"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
toy_ast.workspace = true
toy_cst.workspace = true
toy_resolve.workspace = true

miette.workspace = true
thiserror.workspace = true
lasso.workspace = true
la-arena.workspace = true

[dev-dependencies]
toy_parser.workspace = true
