[package]
name = "playground-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"

# Internal crates
analyse = { path = "../analyse" }
ast = { path = "../ast" }
hir = { path = "../hir" }
infer = { path = "../infer" }
mir = { path = "../mir" }
parse = { path = "../parse" }
compile = { path = "../compile" }
vm = { path = "../vm" }
